[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "dejavu_fonts", "freefont_ttf"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python main.py"
